version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test-client:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd textthoughts-client
            - run: npm install
            - run: npm test
workflows:
    build-and-test-client:
      jobs:
        - build-and-test